services:
  ffc-ffd-business:
    build:
      context: .
      target: production
    image: ffc-ffd-business
    container_name: ffc-ffd-business
    environment:
      APPINSIGHTS_CLOUDROLE: ffc-ffd-business-local
      APPINSIGHTS_CONNECTIONSTRING: ${APPINSIGHTS_CONNECTIONSTRING}
      AUTH_HOST: ${AUTH_HOST:-http://ffc-ffd-proxy:3000}
      GATEWAY_HOST: ${GATEWAY_HOST:-http://localhost:3000}
