services:
  ffc-ffd-business:
    build:
      context: .
      target: production
    image: ffc-ffd-business
    container_name: ffc-ffd-business
    environment:
      APPINSIGHTS_CLOUDROLE: ffc-ffd-business-local
      APPINSIGHTS_CONNECTIONSTRING: ${APPINSIGHTS_CONNECTIONSTRING}
      GATEWAY_URL: ${GATEWAY_URL:-http://localhost:3000}
